### ISSUE TITLE
Remove --accept-defaults flag from the cluster join command

### ISSUE THREAD

**Issue by dgtlntv** [canonical/maas-anvil#73]
The configuration of the cluster should be set on the bootstrap node. So it seems to be a bug that the `--accept-defaults` flag exists on the `cluster join` command, as there should be nothing for the joining node to accept defaults from.

**Comment by skatsaounis** [comment]
What about bootstrapping the first node only as `database` and then joining a second node as `haproxy`? The prompt for haproxy will appear only when joining the second node. So it is valid to say that instead of getting the prompt, you want to accept the defaults during join. Is this a fair point for the continuity of the `--acept-defaults` flag in the `cluster join` command?

**Comment by dgtlntv** [comment]
Ah yeah, that makes sense. Thanks for answering! :)
